Feat/landing page디자인구현
kjh9852/Rolling pull request #10
Opened 2024-07-15 10:14 UTC by BossTeemo

### 변경 사항
- **`LandingPage` 를 구현했습니다:** 
`LandingDetail` 컴포넌트를 만들어서 거기에 일단 전부 구현해놨습니다. 
컴포넌트를 어떻게 분리해야할지 잘 모르겠어서 
일단 `LandingDetail` 에 모두 구현한 상태인데, 
나중에 기능구현하면서 분리해볼 생각입니다.

- `assets/image`에 `LandingDetail` 구현에 필요한 이미지파일인 `cardImg1`과 `cardImg2` 를 추가했습니다.

- **`HeaderContainer` 가 항상 상단에 있을 수 있도록 `z-index: 1000;` 을 추가했습니다.**

### 변경 이유
사용자 로그인을 통해 개인화된 서비스를 제공하기 위함입니다.

### 관련 이슈
- closes #12345

### 스크린샷

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/74c67d5f-178d-4b95-8f48-3d756b832dd9">

![로그인 화면](URL 또는 경로)

### 테스트
변경 사항에 대한 테스트가 포함되어 있는지, 어떻게 테스트했는지 설명합니다.
- 유닛 테스트 추가
- 통합 테스트 수행
- 로컬 환경에서 수동 테스트 완료

2024-07-15 16:46 UTC, kjh9852 requested changes
리뷰에 수정사항만 수정해주시면 될 것 같습니다
고생하셨어용 😃

2024-07-15 16:46 UTC, kjh9852 commented on src/components/LandingPage/LandingDetail.jsx
> +import '../../assets/style/reset.css';
reset은 전역으로 스타일이 깔린 상태라서 굳이 안가져오셔도 됩니당

2024-07-15 16:46 UTC, kjh9852 commented on src/components/common/Section.jsx
> +  align-items: center;
Section 컴포넌트에서 추가가 되면 flex 옵션이 필요없는곳에서는 쓰기 불편할것 같아요
그래서 직접 수정보다는 Section 컴포넌트를 상속받는 styled-component를 만드는게 좋아보입니당

2024-07-15 16:46 UTC, kjh9852 commented on src/ui/Header.jsx
> +  z-index: 1000;
없이도 header가 다른 콘텐츠에 가려지지 않는데 이유가 있나요?

2024-07-15 16:46 UTC, kjh9852 commented on src/components/LandingPage/LandingDetail.jsx
> +    <Section>
Section 컴포넌트 css 관련된 내용이랑 연계됩니당
예를 들어
``` javscripit
const LandingSection = steyld(Section)`
  display: flex;
  flex-direction: column;
  align-items: center;
`;
이렇게 하는거죠 이렇게 쓰는게 재사용성이 더 좋아보입니당

2024-07-15 16:46 UTC, kjh9852 commented on src/components/LandingPage/LandingDetail.jsx
> +  }
actvie는 굳이 필요없을것 같아요

2024-07-15 16:46 UTC, kjh9852 commented on src/components/LandingPage/LandingDetail.jsx
> +    box-shadow 0.3s ease;
box-shadow 속성이 없는데 transition으로 들어간 이유가 있을까요~?

2024-07-15 16:46 UTC, kjh9852 commented on src/components/LandingPage/LandingDetail.jsx
> +  letter-spacing: -0.01em;
flex 관련 css 들은 없어도 될 것 같습니다~
letter-spacing: -0.01em에서 단위를 em으로 준 이유가 있을까요~?

2024-07-15 16:49 UTC, Injaeeee approved these changes
고생하셨습니다 세환님!

2024-07-15 18:35 UTC, kjh9852 commented on src/components/LandingPage/LandingDetail.jsx
> +const Title = styled.div`
div보다 h2로 들어가는게 좋을 것 같아용

2024-07-16 05:07 UTC, BossTeemo commented
> 리뷰에 수정사항만 수정해주시면 될 것 같습니다 고생하셨어용 😃

수정완료했습니다! 확인부탁드려요

2024-07-16 05:12 UTC, kjh9852 approved these changes
수정 확인했습니당

2024-07-16 05:14 UTC, merged

2024-07-18 10:40 UTC, JaeSang1998 commented on src/components/LandingPage/LandingDetail.jsx
> +const Title = styled.h2`
하이

2024-07-18 10:41 UTC, JaeSang1998 commented on src/components/LandingPage/LandingDetail.jsx
> +    box-shadow 0.3s ease;
하이

2024-07-18 10:41 UTC, BossTeemo commented on src/components/LandingPage/LandingDetail.jsx
> +  letter-spacing: -0.01em;
letter-spacing지우면 디자인과 달라지네요. 버튼안에 글자가 깨집니다.
그래서 그냥 놔두겠습니다.

2024-07-18 10:41 UTC, BossTeemo commented on src/components/LandingPage/LandingDetail.jsx
> +    <Section>
감사합니다! 이런방법이있었네요~ 적용했습니다!

2024-07-18 10:41 UTC, BossTeemo commented on src/ui/Header.jsx
> +  z-index: 1000;
확실하게 해주는게 좋을것같아서 추가해봤습니다!

2024-07-18 10:42 UTC, JaeSang1998 commented on src/components/LandingPage/LandingDetail.jsx
> +const Title = styled.h2`
바로 답변하기